// <auto-generated />
using Efc03SqlServerConsole.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Efc03SqlServerConsole.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Efc03SqlServerConsole.Data.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("RegionId");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Municipalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Praha",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Liberec",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jablonec nad Nisou",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Semily",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Frýdlant",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hejnice",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hradec Králové",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ústí nad Labem",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "Děčín",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 10,
                            Name = "Teplice",
                            RegionId = 4
                        });
                });

            modelBuilder.Entity("Efc03SqlServerConsole.Data.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hlavní město Praha"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Liberecký kraj"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Královéhradecký kraj"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ústecký kraj"
                        });
                });

            modelBuilder.Entity("Efc03SqlServerConsole.Data.Municipality", b =>
                {
                    b.HasOne("Efc03SqlServerConsole.Data.Region", "Region")
                        .WithMany("Municipalities")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
