// <auto-generated />
using System;
using Efc05SqlServerWeb.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Efc05SqlServerWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191103202428_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Efc05SqlServerWeb.Model.Exhibit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Exhibits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mona Lisa"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Stvoření Adama"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dáma s hranostajem"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Poslední večeře"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dívka s perlou"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Slunečnice"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Výkřik"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hvězdná noc"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Zrození Venuše"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Přetrvávání vzpomínky"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Lekníny"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Harlekín"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Noční hlídka"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Moulin Rouge"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
