// <auto-generated />
using System;
using Efc05SqlServerWeb.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Efc05SqlServerWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191110213411_Years")]
    partial class Years
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Efc05SqlServerWeb.Model.Exhibit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Exhibits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mona Lisa",
                            Year = 1506
                        },
                        new
                        {
                            Id = 2,
                            Name = "Stvoření Adama",
                            Year = 1512
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dáma s hranostajem",
                            Year = 1450
                        },
                        new
                        {
                            Id = 4,
                            Name = "Poslední večeře",
                            Year = 1498
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dívka s perlou",
                            Year = 1665
                        },
                        new
                        {
                            Id = 6,
                            Name = "Slunečnice",
                            Year = 1888
                        },
                        new
                        {
                            Id = 7,
                            Name = "Výkřik",
                            Year = 1893
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hvězdná noc",
                            Year = 1889
                        },
                        new
                        {
                            Id = 9,
                            Name = "Zrození Venuše",
                            Year = 1486
                        },
                        new
                        {
                            Id = 10,
                            Name = "Přetrvávání vzpomínky",
                            Year = 1931
                        },
                        new
                        {
                            Id = 11,
                            Name = "Lekníny",
                            Year = 1914
                        },
                        new
                        {
                            Id = 12,
                            Name = "Harlekýn",
                            Year = 1923
                        },
                        new
                        {
                            Id = 13,
                            Name = "Noční hlídka",
                            Year = 1642
                        },
                        new
                        {
                            Id = 14,
                            Name = "Moulin Rouge",
                            Year = 1895
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
